# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release/*
- develop
- feature/*

pr: none

variables:
- group: situmArtifactory
- group: Passwords
- name: xcodeVersion
  value: /Applications/Xcode_13.2.1.app

resources:
  repositories:
  - repository: sys_kubernetes_templates
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/sys-kubernetes-templates.git
    ref: 'feature/SIS-604'

pool:
  vmImage: 'macOS-11'

steps:
- checkout: self
  fetchDepth: 1
  fetchTags: false
  displayName: Checkout self


- template: azure-templates/upload-sharepoint.yml@sys_kubernetes_templates
  parameters:
    prepare_sharepoint: False
    properties_file: 'scripts/framework.properties'
    prepare_ndk: false

- ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: Certificados.p12
  
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 566ecab6-e43e-473a-9daa-2456d675f241.mobileprovision
      removeProfile: true
    
    # release/* branches:
- ${{ if contains(variables['Build.SourceBranch'], 'release/') }}:
    - template: azure/create_artifacts.yml
      parameters:
        buildTypes:
        - name: Release
          zipName: SitumWayfinding.appledoc-$(version).zip
          reponame: lib-release-local-private/iOS/SitumWayfinding/$(branch)/$(version)/
        xcodeVersion: $(xcodeVersion)

- ${{ if or(contains(variables['Build.SourceBranch'], 'feature/SIS-603'),contains(variables['Build.SourceBranchName'],'develop')) }}:
    - template: azure/create_artifacts.yml
      parameters:
        buildTypes:
        - name: Debug
          zipName: SitumWayfinding.appledoc-$(branch)-$(version)-DEV.zip
          reponame: libs-snapshot-local-private/iOS/SitumWayfinding/$(branch)/$(version)
        xcodeVersion: $(xcodeVersion)


- ${{ if eq(variables['Build.SourceBranchName'], 'feature/SIS-604') }}:
  - task: DownloadSecureFile@1
    name: github_token
    inputs:
      secureFile: github_token
  
  - template: azure-templates/publish_artifacts.yml@sys_kubernetes_templates
    parameters:
      system: "N/A"
      server: "github"


