# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release/*
- develop
- feature/*

pr: none

variables:
- group: situmArtifactory
- group: Passwords
- group: SoftwareVersions

resources:
  repositories:
  - repository: sys_kubernetes_templates
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/sys-kubernetes-templates.git
    ref: master
  - repository: web_developers
    type: bitbucket
    endpoint: Bitbucket - sistemas
    name: situm/web-developers.git
    ref: master

pool:
  vmImage: $(macOSVersion)

steps:
- checkout: self
  fetchDepth: 1
  fetchTags: false
  displayName: Checkout self


- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  - template: azure-templates/upload-sharepoint.yml@sys_kubernetes_templates
    parameters:
      prepare_sharepoint: False
      properties_file: 'ios-swift-library-wayfinding/scripts/framework.properties'
      prepare_ndk: false

- ${{ if ne(variables['Build.SourceBranchName'], 'master') }}:
  - template: azure-templates/upload-sharepoint.yml@sys_kubernetes_templates
    parameters:
      prepare_sharepoint: False
      properties_file: 'scripts/framework.properties'
      prepare_ndk: false

  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: Certificados.p12
  
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 566ecab6-e43e-473a-9daa-2456d675f241.mobileprovision
      removeProfile: true
    
    # release/* branches:
- ${{ if contains(variables['Build.SourceBranch'], 'release/') }}:
    - template: azure/create_artifacts.yml
      parameters:
        buildTypes:
        - name: Release
          zipName: SitumWayfinding.appledoc-$(version).zip
          reponame: lib-release-local-private/iOS/SitumWayfinding/$(branch)/$(version)/
        xcodeVersion: $(xcodeVersion)

- ${{ if or(contains(variables['Build.SourceBranch'], 'feature/'),contains(variables['Build.SourceBranchName'],'develop')) }}:
    - template: azure/create_artifacts.yml
      parameters:
        buildTypes:
        - name: Debug
          zipName: SitumWayfinding.appledoc-$(branch)-$(version)-DEV.zip
          reponame: libs-snapshot-local-private/iOS/SitumWayfinding/$(branch)/$(version)
        xcodeVersion: $(xcodeVersion)


- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:

  - template: azure-templates/publish_release.yml@sys_kubernetes_templates
    parameters:
      bitbucket:
        bitbucket_user: situmops
      system: "N/A"
      server: "github"
      repoFolder: "ios-swift-library-wayfinding"

  
  - task: DownloadSecureFile@1
    name: netrc
    inputs:
      secureFile: netrc
  
  - bash: |
      echo -e "\n[+] Configure pod trunk register........\n"
      cp $(netrc.secureFilePath) ~/.netrc
      chmod 0600 ~/.netrc
  
      echo -e "\n[+] Show pod trunk sessions...........\n"
      pod trunk me
  
      echo -e "\n[+] Pod push WYF..........."
      pod trunk push SitumWayfinding.podspec --skip-import-validation --allow-warnings
  
    displayName: Push podspec
  
  - template: azure-templates/commit-doc.yaml@sys_kubernetes_templates
    parameters:
      version: $(version)
      docPath: "sdk_documentation/wayfinding/appledoc" 
      system: "ios"
      release: "ios-wayfinding"
      artifactId: "SitumWayfinding"
      bitbucket:
        bitbucket_user: $(bitbucket_user)
        bitbucket_pass: $(bitbucket_pass)
    
